### ISSUE TITLE
Release wither 0.1.0

### ISSUE THREAD

**Issue by torbjorn** [torbjorn/wither#3]
First release:

* [x] `usethis::use_news_md()`
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `usethis::use_github_links()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `git push`
* [x] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] Finish & publish blog post
* [ ] Add link to blog post in pkgdown news menu
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`
* [x] `usethis::use_news_md()`
* [ ] Share on social media

**Comment by krlmlr** [comment]
We can use GitHub Actions to make sure R-devel checks pass now and in the future:

```r
usethis::use_github_action()
```

**Comment by torbjorn** [comment]
It's not so much catching the occational test error or check warning that I'm struggling with, I just don't know how to make it pass.

For the time it's still up there, here is the check log on windows r-devel:

https://win-builder.r-project.org/Sf0qL9z63iPi/00check.log , see specifically the line:

    Error: [EPERM] Failed to open 'D:/RCompile/.here261a87f73197d': operation not permitted

(_here()_ is D:/RCompile, unless I'm mistaken)

I even tried testing if here() is writable and skip tests and abort example code early if not, but it didnt help, it seems writable, Im just not allowed to touch that file.

The first option on win-builder, **R-release**, works fine. It's just R-devel and R-oldrelease that fail: https://win-builder.r-project.org/upload.aspx

**Comment by krlmlr** [comment]
Can you make the example run in a temporary directory, and clean up afterward? They will be less clear, but unfortunately, an initial CRAN submission requires examples. A vignette might be more suitable for an example that is easier to understand for new users.

**Comment by torbjorn** [comment]
Essentially a `setwd(some_existing_tempdir)` before the rest of the example code (and test code for that matter)?

It could work, however there is a timing issue the way I see it.

The example code gets executed in a context where this library is already loaded. (see here for an example: https://win-builder.r-project.org/Sf0qL9z63iPi/examples_and_tests/wither-Ex.R , the R code generated to run the example code). There's a `library('wither')` injected _before_ the example code in that script. Since this library loads here, here's root directory gets set to the initial working directory, before my `setwd(...)` happens.

Essentially I'd have to also manually change the here() root before any example code runs. Ill try this as a debuging operation, but it wont be pretty :/

**Comment by torbjorn** [comment]
Ok, we have likely solved this by using any existing file in the directory we're switching to (and switching back). If empty, we still create a .hereXXX tempfile though.

**Comment by torbjorn** [comment]
@krlmlr we're currently awaiting feedback from CRAN. 

May I ask - as alluded to earlier, the way we temporarily redirect here() is a bit of a hack, maybe (but using only functions exported from here), and requires that there is a file present in both the new temproary here() root and the current here() root (and if not will somewhat rudely create temporary temp files in those directories)

Would it make sense to more formally support changing here() root in the here package, or would it perhaps go against its philosophy?
